language: java
script: ant
jdk:
  - oraclejdk8
addons:
  artifacts:
    debug: true
    paths:
      - dist/counter.war
    target_paths: travis-ci-bet/$TRAVIS_BUILD_NUMBER
    #working_dir: WORKING_DIR
    bucket: travis-ci-bet
    s3_region: us-east-1 

# get us on the new container based builds, we're not using any fancyness
sudo: false  

branches:
  only:
  - master
  
notifications:
  email: false